/**
 * @type {{
 *   currentSurah: number,
 *   currentAyahIndex: number,
 *   currentReciter: string,
 *   currentTafsirEdition: string,
 *   surahData: object|null,
 *   surahList: Array<{number: number, name: string, englishName: string, numberOfAyahs: number}>,
 *   surahCache: Map,
 *   ayahsAudios: string[],
 *   isPlaying: boolean,
 *   hifdhMode: boolean,
 *   repeatMode: boolean,
 *   repeatFrom: number,
 *   repeatTo: number,
 *   repeatTimes: number,
 *   repeatCounter: number,
 *   fontSize: number,
 *   nightMode: boolean,
 *   autoSave: boolean,
 *   azanEnabled: boolean,
 *   azanFajrEnabled: boolean,
 *   city: string,
 *   country: string,
 *   method: string,
 *   prayerTimes: object|null,
 *   lastAzanFired: string|null,
 *   favorites: Array<{key: string, surah: number, surahName: string, ayah: number, text: string, timestamp: number}>,
 *   bookmark: {surah: number, surahName: string, ayah: number, text: string, timestamp: number}|null,
 *   pendingTafsirAfterLoad: string|null,
 *   playerCollapsed: boolean,
 *   barCollapsed: boolean,
 *   azanPlaying: boolean,
 *   loadingSurah: number|null,
 *   mushafMode: boolean,
 *   currentPage: number,
 *   fullQuranText: Array<{surah: number, surahName: string, ayah: number, text: string, normalized: string}>|null,
 *   fullQuranLoaded: boolean,
 *   ayahWordElements: HTMLElement[]|null,
 *   translationEnabled: boolean,
 *   currentTranslation: string|null,
 *   translationData: object|null,
 *   adhkarSettings: object|null,
 *   adhkarPanelOpen: boolean,
 *   adhkarActiveTab: string|null,
 *   lastAdhkarFired: string|null,
 *   adhkarNotificationTimer: number|null,
 *   _voiceListening: boolean,
 *   _voiceRecognition: object|null,
 *   _smartTvState: number,
 *   _smartTvAudioSrc: string,
 *   surahOffsets: Array<{surahNum: number, startAbs: number, count: number, name: string}>|null,
 *   backgroundsList: Array<{id: string, name: string, type?: string, css?: string}>|null
 * }}
 */
export let state = /** @type {any} */ ({});
